# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-JV2TcaABRBQ8BIhrPfssLb9qCLoxZw
"""

import pyotp

# Your secret key (replace this with your actual secret)
secret = 'JCVZNBDNXKNFIYKLHZFLTOOOHVYFPJPK'  # Example secret key

# Create a TOTP object
totp = pyotp.TOTP(secret)

# Generate the current TOTP
current_totp = totp.now()

print(f"Current TOTP: {current_totp}")